/****************************************************************
 HspMatrix.H
 william.majoros@duke.edu

 This is open-source software, governed by the Gnu General Public License (GPL) version 3 
 (see www.opensource.org).
 ****************************************************************/
#ifndef INCL_HspMatrix_H
#define INCL_HspMatrix_H
#include <iostream>
using namespace std;


class HspMatrix
{
public:
  //  HspMatrix(MultSeqAlignment &,MultSeqAligment &);
};

#endif

